# These are supported funding model platforms

github: sonnettie-tech sonnettie # [user1, user2]
patreon: sonnettie-tech
open_collective: sonnettie-tech
ko_fi: sonnettie-tech
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sonnettie-tech
issuehunt: sonnettie-tech
otechie: sonnettie-tech
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
